### ISSUE TITLE
💡 RFC: When capo is set, edit the chart in the key of the capo 

### ISSUE THREAD

**Issue by isaiahdahl** [bettermusic/ChordSheetJS#216]
### Background & Motivation

When the capo is set, you should be editing the chart in the key of the song that is key + capo, not the original key of the song.

This is an example of what it will currently do

```
{key: F}
{capo: 1}
{c: Verse 1 *1}
My [Dm7]heart has always [C/E]longed for something[F] more
I [Dm7]searched the stars to [Bb]knock on Heaven's [F2]door
Cre - [Dm7]ation groans for [C2/E]God to be re [F2]- vealed
```

```
{key: F}
{c: Verse 1 *1}
My [Dm7]heart has always [C/E]longed for something[F] more
I [Dm7]searched the stars to [Bb]knock on Heaven's [F2]door
Cre - [Dm7]ation groans for [C2/E]God to be re [F2]- vealed
```

The above will render different HTML. Where the capo:1 example will render the chart in the key of E.

The problem is it doesn't seem right to be editing the chart, set the capo to 1, and then continue editing the chart in the key of F. 

![CleanShot 2022-07-13 at 16 50 26](https://user-images.githubusercontent.com/23046374/178855962-f6f506e5-7cfb-4adb-9e17-56246e12d640.png)

### Possible solutions

Make it so when capo is set, it transposes the chordpro to the new key. 
So that when you're editing the chordpro, the chords you change, match with what's rendered.

**Comment by martijnversluis** [comment]
Interesting one!

My initial thought was: might it make sense to differentiate between _editing key_ and _rendering key_ in the controls? Where only the _rendering key_ affects the generated output

Then I lookup the definition for `{capo}`. If I understand it correctly having a chord sheet with `{key: E}` and `{capo: 1}` would result in key `F`. Do you think that's correct? https://www.chordpro.org/chordpro/directives-capo/

**Comment by isaiahdahl** [comment]
I like your thoughts about differentiating between editing key and rendering key, similar to how Planning Center does it.

The definition for the capo directive seems weird to me, but it does share one element of similarity to what I was thinking in the sense that you edit the chart in the key that would be the Key-Capo key.

This is how I understand the definition for chordpro:
```
{key: D}
{capo: 2}

This song is [D]edited in key of D
The chart is rendered in key of D
The guitarist/pianist is playing in the key of D
The song's key is F
```

How we currently have it written.
```
{key: F}
{capo: 2}

This song is edited in key of F
The chart is rendered in key of D
The guitarist/pianist is playing in the key of D
The song's key is F
```

How I was thinking it should be written:
```
{key: F}
{capo: 2}

This song is edited in key of D
The chart is rendered in key of D (referencing the original key still)
The guitarist/pianist is playing in the key of D
The song's key is F
```

The problem I have with chordpro's definition of the capo directive is that if you want to change the capo up one or two becasue the song is low, you have to calculate what key it's suppose to go to in your head. Instead of just changing the capo number. 

For instance, if I wanted to go to capo 4 so I could play in C. I'd have to change the chordpro to be this.
```
{key: C}
{capo: 4}

This song is edited in key of C
The chart is rendered in key of C
The guitarist/pianist is playing in the key of C
The song's key is F
```
Changing two directives instead of 1.

I find this really impractical. Although in the same breath. most people will not be editing the chordpro to set the capo, they will be using a dropdown ... but I still think it's odd, but maybe it's just becasue I've never used chordpro that does it like what's defined, and I'm just not used to it.

I'm not 100% sure where to go from here. I wouldn't be opposed to changing things to align with the "standard" becasue for our use case, people aren't really going to be editing the capo in the chordpro that often if ever anyways. Becasue dropdowns will just be easier. But it just seems odd that the concert key, is not referenced in the chordpro and that you have to musically calculate what the actual key is if you want to change the capo manually.

**Comment by martijnversluis** [comment]
@isaiahdahl I would logic-wise stay true to the Chordpro standard:

```
{key: D}
{capo: 3}

This song is [D]edited in key of D
The chart is by default rendered in key of D, but the user can choose to preview in either D or F
The guitarist is playing in the key of D. The pianist is probably playing in F, or using the transpose button 😉 
The song's key is F, so the PDF downloads are (similar to PCO): "F" or "D (capo 3)"
```

Maybe it's useful to have a `key:` parameter for formatters, to allow rendering in any key (on the fly) without having to transpose the song first:

```js
const song = new ChordProParser().parse(chordPro);
const sheetInD = new HtmlDivFormater().format(song);
const sheetInF = new HtmlDivFormatter().format(song, { key: 'F' });
```

**Comment by isaiahdahl** [comment]
@martijnversluis I like the idea of a key parameter for formatters. 

I think that could expand to be more of and formatter config containing more the just the key.
